import { SHARED_VARIABLE } from "@share/common";
import { useCounter } from "@store/counter";
import Head from "next/head";

export default function Home() {
  const { count, increase } = useCounter();
  console.log("count->", count);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta
          name="description"
          content="Generated by create-t3-app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>{SHARED_VARIABLE}</div>
        <button onClick={increase}>increase</button>
      </main>
    </>
  );
}
